#!/usr/bin/env node
/**
 * The rotation worksheet, held to the two files it is derived from.
 *
 * WHY THIS EXISTS
 * The worksheet decides the order of the estate's most consequential remaining work: which
 * endpoint keys need a new URL after ITEM-22's rotation, and which do not. If it drifts from
 * endpoint-workflow-ids.json or from the disclosed set, it sends the operator to re-capture URLs
 * that did not change, or — worse — tells them a key is safe when its flow's token was leaked.
 *
 * It also has one property that is not about arithmetic: it must never contain a signature. It is
 * generated by reading them.
 *
 * Run: node tests/rotation-worksheet.test.mjs
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(path.join(ROOT, p), 'utf8');
const DIR = 'docs/deployment/rotation';
const w = JSON.parse(read(`${DIR}/rotation-worksheet.json`));
const md = read(`${DIR}/ROTATION.md`);
const template = read(`${DIR}/values.template.txt`);
const MAP = JSON.parse(read('docs/reference/endpoint-workflow-ids.json'));

let passed = 0, failed = 0;
const ok = (label, cond, detail = '') => {
  if (cond) { passed++; console.log(`  ✅ ${label}`); }
  else { failed++; console.log(`  ❌ ${label}${detail ? `\n       ${detail}` : ''}`); }
};

console.log('\nThe rotation worksheet\n');

console.log('  IT MATCHES THE ENDPOINT MAP');
const mapKeys = [...Object.keys(MAP.internal || {}), ...Object.keys(MAP.portal || {})];
ok(`every endpoint key is present (${mapKeys.length})`,
   mapKeys.every((k) => w.rows.some((r) => r.key === k)),
   mapKeys.filter((k) => !w.rows.some((r) => r.key === k)).join(', '));
ok('and it invents none', w.rows.every((r) => mapKeys.includes(r.key)));
ok('each row carries the workflow id the map records',
   w.rows.every((r) => (MAP[r.scope][r.key].workflowId || null) === r.workflowId));
ok('the counts add up to the total',
   w.endpointKeys.mustRecapture + w.endpointKeys.unaffected + w.endpointKeys.undetermined ===
   w.endpointKeys.total && w.endpointKeys.total === w.rows.length);

console.log('\n  THE VERDICTS ARE THE ONES THE EVIDENCE SUPPORTS');
ok('a key with no workflow id is UNDETERMINED, never UNAFFECTED',
   w.rows.every((r) => (r.workflowId === null) === (r.status === 'UNDETERMINED')),
   'calling an unknown key safe is the one error here that costs an outage');
ok('every MUST_RECAPTURE row names a signature count above zero',
   w.rows.filter((r) => r.status === 'MUST_RECAPTURE').every((r) => r.signatures > 0));
ok('every UNAFFECTED row carries no signature count',
   w.rows.filter((r) => r.status === 'UNAFFECTED').every((r) => r.signatures === 0));
ok('the flows behind no key are disjoint from the flows behind a key',
   w.flowsBehindNoKey.workflowIds.every((id) =>
     !w.rows.some((r) => r.workflowId === id && r.status === 'MUST_RECAPTURE')));
ok('it says what "behind no key" does and does not establish',
   /does NOT establish that they are\s*\n?\s*unused/.test(w.flowsBehindNoKey.meaning));

console.log('\n  THE VALUES TEMPLATE IS COMPLETE');
const templated = [...template.matchAll(/^([A-Z_]+)=$/gm)].map((m) => m[1]);
ok(`it lists every endpoint key once (${templated.length})`,
   templated.length === mapKeys.length && new Set(templated).size === templated.length,
   `${templated.length} lines for ${mapKeys.length} keys`);
ok('and every one is a real key', templated.every((k) => mapKeys.includes(k)));
ok('it warns that the file holds bearer credentials and must be deleted',
   /BEARER CREDENTIALS/i.test(template) && /delete it once/i.test(template));

console.log('\n  IT LEAKS NOTHING');
const all = md + JSON.stringify(w) + template;
ok('no signature appears in any generated file', !/[?&]sig=[A-Za-z0-9_-]{20,}/.test(all),
   'the generator reads signatures to produce this and must never write one');
ok('no trigger URL appears either', !/logic\.azure\.com.*paths\/invoke/.test(all));

console.log('\n  THE PROCEDURE IS THE ONE THAT WAS PROVEN');
ok('step 4 passes --force, without which a post-rotation re-run keeps the revoked URLs',
   /npm run setup -- --values <file> --force/.test(md));
ok('it records that the chain was exercised, and that the negative control fired',
   /negative control fires/i.test(md) && /WRONG FLOW/.test(md));
ok('it states the limit of the check — a revoked token still reads as correct',
   /revoked token reads as\s*\n?correct/.test(md));
ok('it corrects CFG-2, rather than repeating that it waits on the whole rotation',
   /## What this corrects/.test(md) && /only partly true/.test(md));

console.log(`\n${failed ? '❌' : '✅'} ${passed} passed, ${failed} failed\n`);
process.exit(failed ? 1 : 0);
