/* GENERATED by npm run orgrouting — do not edit. Source: docs/reference/approved/category-matrix.csv */

/**
 * The approved category matrix. Agency approval of 2026-09-08 closes MANUAL-1.
 *
 * This replaces the provisional eleven-kind routing table, which was a reading of the fallback
 * matrix rather than a statement of the operating model. Routing is now Category + Subcategory
 * → a responsible unit, a supporting unit, and up to three units informed.
 *
 * ⚠️ NO PERSONAL DATA. Rows name DSU keys, never people. Resolve a key to a mailbox with
 * mailboxFor() from organizational-units.config.js, which returns a role mailbox; resolve a key
 * to a PERSON through the DGO_UserDirectory SharePoint list at runtime.
 *
 * ackDays and dueDays come from the approved SPT and EPT columns. A row whose timeline the
 * agency recorded as "Ongoing" carries null rather than an invented number.
 */
export const CategoryMatrix = Object.freeze([
  Object.freeze({ category: "Administrative Matters", categoryCode: "ADM", subcategory: "Human Resources", subcategoryCode: "HRM", dsuKey: "HRM", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "AdminServicesList", priority: "Medium", ackDays: 5, dueDays: 7, description: "Policies procedures and activities related to HR management" }),
  Object.freeze({ category: "Administrative Matters", categoryCode: "ADM", subcategory: "Administrative Services", subcategoryCode: "ADS", dsuKey: "AGS", supportDsuKey: "PM", informDsu: Object.freeze(["DGO", "CEO", "PU"]), listName: "AdminServicesList", priority: "Medium", ackDays: 3, dueDays: 5, description: "General administrative functions within NITDA" }),
  Object.freeze({ category: "Administrative Matters", categoryCode: "HRM", subcategory: "General Administration", subcategoryCode: "GEN", dsuKey: "AGS", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "GeneralAdminList", priority: "Medium", ackDays: 3, dueDays: 7, description: "Oversight of all general administrative activities" }),
  Object.freeze({ category: "Administrative Matters", categoryCode: "ADM", subcategory: "Scholarships", subcategoryCode: "SCH", dsuKey: "AGS", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "ScholarshipList", priority: "Medium", ackDays: null, dueDays: null, description: "Scholarship programs within NITDA" }),
  Object.freeze({ category: "Contracts and Services", categoryCode: "CAS", subcategory: "Procurement", subcategoryCode: "PRC", dsuKey: "PU", supportDsuKey: "PM", informDsu: Object.freeze(["DGO", "CEO"]), listName: "ProcurementList", priority: "Medium", ackDays: 7, dueDays: 10, description: "Procurement of goods and services" }),
  Object.freeze({ category: "Contracts and Services", categoryCode: "CAS", subcategory: "Projects Management", subcategoryCode: "PRM", dsuKey: "PM", supportDsuKey: "PU", informDsu: Object.freeze(["DGO", "CEO"]), listName: "ProcurementList", priority: "Medium", ackDays: 7, dueDays: 10, description: "Management of procurement processes for projects" }),
  Object.freeze({ category: "Contracts and Services", categoryCode: "CAS", subcategory: "Legal Services", subcategoryCode: "LGS", dsuKey: "LBMU", supportDsuKey: "PU", informDsu: Object.freeze(["DGO", "CEO", "PM"]), listName: "LegalServicesList", priority: "Medium", ackDays: 7, dueDays: 10, description: "Legal engagements in contracts and service agreements" }),
  Object.freeze({ category: "Engagements and Events", categoryCode: "EAI", subcategory: "Events", subcategoryCode: "EVE", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO", "PA", "CCMR"]), listName: "EventsList", priority: "Medium", ackDays: 14, dueDays: 30, description: "Events organized or hosted by NITDA" }),
  Object.freeze({ category: "Engagements and Events", categoryCode: "EAI", subcategory: "Invitations", subcategoryCode: "INV", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO", "PA"]), listName: "InvitationsList", priority: "High", ackDays: null, dueDays: null, description: "Invitations extended for NITDA participation in activities" }),
  Object.freeze({ category: "Engagements and Events", categoryCode: "EAI", subcategory: "High-Level Engagements", subcategoryCode: "HLE", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO", "PA"]), listName: "HighLevelEngagementsList", priority: "High", ackDays: 7, dueDays: 14, description: "High-level engagements involving key stakeholders" }),
  Object.freeze({ category: "Finance Matters", categoryCode: "FIN", subcategory: "Budgeting", subcategoryCode: "BUD", dsuKey: "BDMU", supportDsuKey: "FMC", informDsu: Object.freeze(["DGO", "CEO"]), listName: "BudgetList", priority: "Medium", ackDays: 10, dueDays: 15, description: "Budget planning allocation and management within NITDA" }),
  Object.freeze({ category: "Finance Matters", categoryCode: "FIN", subcategory: "Expenditure", subcategoryCode: "EXP", dsuKey: "FMC", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "ExpenditureList", priority: "High", ackDays: 5, dueDays: 7, description: "Management and oversight of financial expenditures" }),
  Object.freeze({ category: "Finance Matters", categoryCode: "FIN", subcategory: "Miscellaneous", subcategoryCode: "MSC", dsuKey: "FMC", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "MiscellaneousList", priority: "Medium", ackDays: null, dueDays: null, description: "Miscellaneous financial matters within NITDA" }),
  Object.freeze({ category: "FMCIDE", categoryCode: "MCI", subcategory: "Honourable Minister", subcategoryCode: "HMM", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO"]), listName: "HonourableMinisterList", priority: "High", ackDays: 7, dueDays: 14, description: "Matters relating to the Honourable Minister" }),
  Object.freeze({ category: "FMCIDE", categoryCode: "MCI", subcategory: "Mainstream", subcategoryCode: "MCI", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["CEO"]), listName: "MainstreamList", priority: "High", ackDays: null, dueDays: null, description: "Mainstream FMCIDE matters" }),
  Object.freeze({ category: "GOV TO GOV", categoryCode: "GOV", subcategory: "Regulatory Affairs", subcategoryCode: "REA", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO"]), listName: "InterAgencyCollabList", priority: "Medium", ackDays: null, dueDays: null, description: "Collaborations with other government agencies" }),
  Object.freeze({ category: "GOV TO GOV", categoryCode: "GOV", subcategory: "StakeHolder Engagements", subcategoryCode: "STE", dsuKey: "SMP", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "", priority: "", ackDays: null, dueDays: null, description: "" }),
  Object.freeze({ category: "GOV TO GOV", categoryCode: "GOV", subcategory: "Inter Agency Collaborations", subcategoryCode: "IAC", dsuKey: "SMP", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "", priority: "", ackDays: null, dueDays: null, description: "" }),
  Object.freeze({ category: "Internships", categoryCode: "INI", subcategory: "Industrial Attachment", subcategoryCode: "IAT", dsuKey: "HRM", supportDsuKey: "", informDsu: Object.freeze(["DGO"]), listName: "IndustrialAttachmentList", priority: "Low", ackDays: 5, dueDays: 7, description: "Industrial Attachment internships for students" }),
  Object.freeze({ category: "Internships", categoryCode: "INI", subcategory: "NYSC", subcategoryCode: "NYC", dsuKey: "HRM", supportDsuKey: "", informDsu: Object.freeze(["DGO"]), listName: "InternshipsList", priority: "Low", ackDays: 5, dueDays: 7, description: "Manage internships for National Youth Service Corps members" }),
  Object.freeze({ category: "Interventions", categoryCode: "ITV", subcategory: "Government Agencies", subcategoryCode: "GOV", dsuKey: "PA", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "InterventionsList", priority: "Low", ackDays: 10, dueDays: 15, description: "Manage interventions and collaborations with government agencies" }),
  Object.freeze({ category: "Interventions", categoryCode: "ITV", subcategory: "Private Sector", subcategoryCode: "PRV", dsuKey: "PA", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "InterventionsList", priority: "Low", ackDays: 10, dueDays: 15, description: "Manage interventions and collaborations with private sector" }),
  Object.freeze({ category: "Interventions", categoryCode: "ITV", subcategory: "Legislature", subcategoryCode: "LGS", dsuKey: "PA", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "LegislatureList", priority: "Low", ackDays: 7, dueDays: 10, description: "Legislative collaboration and interventions" }),
  Object.freeze({ category: "Legal Matters", categoryCode: "LGM", subcategory: "N/A", subcategoryCode: "N/A", dsuKey: "LBMU", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "", priority: "High", ackDays: null, dueDays: null, description: "" }),
  Object.freeze({ category: "Legislative Matters", categoryCode: "LLM", subcategory: "House of Representatives", subcategoryCode: "LMH", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO"]), listName: "HouseofRepList", priority: "High", ackDays: null, dueDays: null, description: "Collaboration with the House of Representatives" }),
  Object.freeze({ category: "Legislative Matters", categoryCode: "LLM", subcategory: "Senate", subcategoryCode: "LMS", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO"]), listName: "SenateList", priority: "High", ackDays: null, dueDays: null, description: "Collaboration with the Senate" }),
  Object.freeze({ category: "NITDA Engagements", categoryCode: "NTE", subcategory: "Specialized", subcategoryCode: "SPE", dsuKey: "DGO", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "NITDAEngagementsList", priority: "Medium", ackDays: null, dueDays: null, description: "NITDA-related engagements" }),
  Object.freeze({ category: "NITDA Engagements", categoryCode: "NTE", subcategory: "Tech Innovation", subcategoryCode: "TIN", dsuKey: "CEO", supportDsuKey: "DGO", informDsu: Object.freeze(["DGO", "CEO"]), listName: "TechInnovationList", priority: "Medium", ackDays: null, dueDays: null, description: "NITDA engagements related to technology innovation" }),
  Object.freeze({ category: "NITDA Engagements", categoryCode: "NTE", subcategory: "Long-Term Strategy", subcategoryCode: "LTS", dsuKey: "CPS", supportDsuKey: "DGO", informDsu: Object.freeze(["DGO", "CEO"]), listName: "LongTermStrategyList", priority: "Medium", ackDays: null, dueDays: null, description: "NITDA engagements related to long-term strategies" }),
  Object.freeze({ category: "NITDA Internal Operations", categoryCode: "OPS", subcategory: "Operations", subcategoryCode: "OPS", dsuKey: "DGO", supportDsuKey: "", informDsu: Object.freeze(["GO"]), listName: "OperationsList", priority: "High", ackDays: null, dueDays: null, description: "Internal operational management at NITDA" }),
  Object.freeze({ category: "NITDA Services", categoryCode: "NSS", subcategory: "IT Project Clearance", subcategoryCode: "ITP", dsuKey: "ITPC", supportDsuKey: "ITPCU", informDsu: Object.freeze(["DGO", "CEO"]), listName: "ITClearanceList", priority: "High", ackDays: null, dueDays: null, description: "Manage IT project clearance for NITDA" }),
  Object.freeze({ category: "NITDA Services", categoryCode: "NSS", subcategory: "No Objection", subcategoryCode: "NOB", dsuKey: "RC", supportDsuKey: "RC", informDsu: Object.freeze(["DGO", "CEO"]), listName: "NoObjectionList", priority: "High", ackDays: 7, dueDays: 10, description: "Manage 'No Objection' certifications for ICT projects" }),
  Object.freeze({ category: "NITDA Services", categoryCode: "NSS", subcategory: "General Services", subcategoryCode: "GEN", dsuKey: "DGO", supportDsuKey: "", informDsu: Object.freeze([]), listName: "GeneralServicesList", priority: "Medium", ackDays: null, dueDays: null, description: "General IT services provided by NITDA" }),
  Object.freeze({ category: "NITDA Services", categoryCode: "NSS", subcategory: "Domains", subcategoryCode: "DMS", dsuKey: "DMS", supportDsuKey: "RC", informDsu: Object.freeze(["DGO", "CEO"]), listName: "DomainsList", priority: "Medium", ackDays: null, dueDays: null, description: "Domain name management and services within NITDA" }),
  Object.freeze({ category: "NITDA Services", categoryCode: "NSS", subcategory: "IICP", subcategoryCode: "IIC", dsuKey: "IIC", supportDsuKey: "RC", informDsu: Object.freeze(["DGO", "CEO"]), listName: "NSIList", priority: "High", ackDays: null, dueDays: null, description: "Manage ICT policy and services for NSI" }),
  Object.freeze({ category: "Public Relations", categoryCode: "PRS", subcategory: "N/A", subcategoryCode: "N/A", dsuKey: "CCMR", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "PublicRelationsList", priority: "Medium", ackDays: null, dueDays: null, description: "Public relations and communication for NITDA" }),
  Object.freeze({ category: "Sponsorship And Collaborations", categoryCode: "SSC", subcategory: "Institutional Collaborations", subcategoryCode: "ICP", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO"]), listName: "InstCollabList", priority: "Medium", ackDays: null, dueDays: null, description: "Institutional collaborations and partnerships" }),
  Object.freeze({ category: "Sponsorship And Collaborations", categoryCode: "SSC", subcategory: "International Agreements", subcategoryCode: "IAS", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO"]), listName: "IntlAgreementsList", priority: "Medium", ackDays: null, dueDays: null, description: "International partnerships and agreements" }),
  Object.freeze({ category: "Sponsorship And Collaborations", categoryCode: "SSC", subcategory: "Others", subcategoryCode: "OTH", dsuKey: "CEO", supportDsuKey: "", informDsu: Object.freeze(["DGO"]), listName: "ProposalsList", priority: "Medium", ackDays: null, dueDays: null, description: "Submission and review of proposals" }),
  Object.freeze({ category: "Unclassifieds", categoryCode: "UNC", subcategory: "", subcategoryCode: "", dsuKey: "DGO", supportDsuKey: "", informDsu: Object.freeze([]), listName: "N/A", priority: "N/A", ackDays: null, dueDays: null, description: "N/A" }),
  Object.freeze({ category: "Public Relations", categoryCode: "PRC", subcategory: "Courtesy Visits", subcategoryCode: "CVT", dsuKey: "CCMR", supportDsuKey: "PA", informDsu: Object.freeze(["DGO", "CEO"]), listName: "PublicRelationsList", priority: "Medium", ackDays: null, dueDays: null, description: "Visits by external parties to NITDA for courtesy, relationship-building, or protocol purposes. | Enhance stakeholder engagement." }),
  Object.freeze({ category: "Public Relations", categoryCode: "PRC", subcategory: "Apprecialtions and Recognitions", subcategoryCode: "APR", dsuKey: "CCMR", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO", "PA"]), listName: "PublicRelationsList", priority: "Medium", ackDays: null, dueDays: null, description: "Expressions of gratitude or recognition received by NITDA for its services or contributions. | Document appreciation from external parties.      |" }),
  Object.freeze({ category: "Sponsorship And Collaborations", categoryCode: "SSC", subcategory: "PROPOSALS", subcategoryCode: "PPS", dsuKey: "DGO", supportDsuKey: "", informDsu: Object.freeze([]), listName: "ProposalsList", priority: "", ackDays: null, dueDays: null, description: "Expression of Interest to estabish a desired relationship with NITDA" }),
  Object.freeze({ category: "Interventions", categoryCode: "ITV", subcategory: "Educational Institutions", subcategoryCode: "EDU", dsuKey: "PA", supportDsuKey: "", informDsu: Object.freeze(["DGO", "CEO"]), listName: "", priority: "Low", ackDays: null, dueDays: null, description: "" }),
]);

/** The approved categories, in the order the agency listed them. */
export const ApprovedCategories = Object.freeze([
  "Administrative Matters",
  "Contracts and Services",
  "Engagements and Events",
  "Finance Matters",
  "FMCIDE",
  "GOV TO GOV",
  "Internships",
  "Interventions",
  "Legal Matters",
  "Legislative Matters",
  "NITDA Engagements",
  "NITDA Internal Operations",
  "NITDA Services",
  "Public Relations",
  "Sponsorship And Collaborations",
  "Unclassifieds",
]);

/** Where an unmatched category lands. Approved default: the registry classifies and minutes. */
export const DEFAULT_CATEGORY = 'Unclassifieds';

/** Every row for a category. */
export function subcategoriesOf(category) {
  const c = String(category || '').trim().toLowerCase();
  return CategoryMatrix.filter(r => r.category.toLowerCase() === c);
}

/**
 * A row whose subcategory is the catch-all for its category, if the category has one.
 *
 * Without this, a category with no subcategory given resolves to whichever row happens to sort
 * first — so "General Correspondence" landed on Human Resources purely because Human Resources
 * is the first Administrative Matters row. That is an accident of ordering, not a routing
 * decision, and it is the failure tests/categories.test.mjs exists to catch.
 */
const GENERIC_SUBCATEGORY = /^(general|n[/.]a|others?|mainstream|miscellaneous)/i;

/** The matrix row for a category/subcategory pair, or null. Subcategory optional. */
export function routeFor(category, subcategory) {
  const c = String(category || '').trim().toLowerCase();
  const s = String(subcategory || '').trim().toLowerCase();
  const rows = CategoryMatrix.filter(r => r.category.toLowerCase() === c);
  if (!rows.length) return null;
  const fallback = rows.find(r => GENERIC_SUBCATEGORY.test(r.subcategory)) || rows[0];
  if (!s) return fallback;
  return rows.find(r => r.subcategory.toLowerCase() === s
    || r.subcategoryCode.toLowerCase() === s) || fallback;
}
