/* GENERATED by npm run orgrouting — do not edit. Source: docs/reference/approved/organizational-units.csv */

/**
 * NITDA organizational units, as approved by the agency on 2026-09-08.
 *
 * ⚠️ NO PERSONAL DATA. Every address here is a role mailbox — a unit key, an office name, or
 * one behind a headship prefix. The approved export also carried a personal email for 44 named
 * heads; those are NOT here and must not be added. Individual identity is resolved at runtime
 * from the DGO_UserDirectory SharePoint list. `npm run test:orgrouting` fails if an address
 * that identifies a person appears in this file.
 *
 * headTitle is the title of the POST, not of a person: "DHRM" is whoever directs Human Resource
 * Management, and survives the holder changing.
 */
export const OrganizationalUnits = Object.freeze([
  Object.freeze({ key: "Ag DGCEO", title: "Ag DG/CEO", email: "Ag DGCEO@nitda.gov.ng", headEmail: "", headshipType: "Acting", headTitle: "Ag DGCEO" }),
  Object.freeze({ key: "AIC", title: "Audit and Internal Control Department", email: "AIC@nitda.gov.ng", headEmail: "DAIC@nitda.gov.ng", headshipType: "Acting", headTitle: "Ag. DAIC" }),
  Object.freeze({ key: "BDMU", title: "Budget Development and Monitoring Unit", email: "BDMU@nitda.gov.ng", headEmail: "HBDMU@nitda.gov.ng", headshipType: "Substantive", headTitle: "HBDMU" }),
  Object.freeze({ key: "COMDIR", title: "Committee of Directors", email: "COMDIR@nitda.gov.ng", headEmail: "", headshipType: "N/A", headTitle: "" }),
  Object.freeze({ key: "CERRT", title: "Computer Emergency Readiness and Response Team", email: "CERRT@nitda.gov.ng", headEmail: "CERRT@nitda.gov.ng", headshipType: "N/A", headTitle: "CERRT" }),
  Object.freeze({ key: "CCMR", title: "Corporate Communications and Media Relations Department", email: "CCMR@nitda.gov.ng", headEmail: "DCCMR@nitda.gov.ng", headshipType: "Substantive", headTitle: "DCCMR" }),
  Object.freeze({ key: "CPS", title: "Corporate Planning and Strategy Department", email: "CPS@nitda.gov.ng", headEmail: "DCPS@nitda.gov.ng", headshipType: "Substantive", headTitle: "DCPS" }),
  Object.freeze({ key: "CS", title: "Cybersecurity Department", email: "CS@nitda.gov.ng", headEmail: "DCS@nitda.gov.ng", headshipType: "Substantive", headTitle: "DCS" }),
  Object.freeze({ key: "DGO", title: "DGs Office", email: "DGS@nitda.gov.ng", headEmail: "dgs@nitda.gov.ng", headshipType: "N/A", headTitle: "DGO" }),
  Object.freeze({ key: "DDSD", title: "Digital Development Services Department", email: "DDSD@nitda.gov.ng", headEmail: "DDSD@nitda.gov.ng", headshipType: "Acting", headTitle: "DDSD" }),
  Object.freeze({ key: "CEO", title: "Director-General/CEO", email: "DG@nitda.gov.ng", headEmail: "dg@nitda.gov.ng", headshipType: "Substantive", headTitle: "DGCEO" }),
  Object.freeze({ key: "DMS", title: "Domains Management", email: "Domains@nitda.gov.ng", headEmail: "Domains@nitda.gov.ng", headshipType: "N/A", headTitle: "Domains" }),
  Object.freeze({ key: "eGD", title: "e-Government Department", email: "eGD@nitda.gov.ng", headEmail: "DeGD@nitda.gov.ng", headshipType: "Substantive", headTitle: "DeGD" }),
  Object.freeze({ key: "FMC", title: "Finance Management and Control Department", email: "FMC@nitda.gov.ng", headEmail: "DFMC@nitda.gov.ng", headshipType: "Substantive", headTitle: "DFMC" }),
  Object.freeze({ key: "HRM", title: "Human Resource Management", email: "HRM@nitda.gov.ng", headEmail: "DHRM@nitda.gov.ng", headshipType: "Substantive", headTitle: "DHRM" }),
  Object.freeze({ key: "ITD", title: "Information Technology Department", email: "ITD@nitda.gov.ng", headEmail: "", headshipType: "Substantive", headTitle: "DIT" }),
  Object.freeze({ key: "ITPC", title: "IT Projects Clearance", email: "ITPC@nitda.gov.ng", headEmail: "HITPC@nitda.gov.ng", headshipType: "Substantive", headTitle: "HITPCU" }),
  Object.freeze({ key: "LBMU", title: "Legal Services and Board Matters", email: "LBMU@nitda.gov.ng", headEmail: "HLBMU@nitda.gov.ng", headshipType: "Acting", headTitle: "Ag. HLBMU" }),
  Object.freeze({ key: "IIC", title: "Licensing and Regulations", email: "IICP@nitda.gov.ng", headEmail: "IICP@nitda.gov.ng", headshipType: "N/A", headTitle: "IICP" }),
  Object.freeze({ key: "NCAIR", title: "National Centre for Artificial Intelligence and Robotics", email: "NCAIR@nitda.gov.ng", headEmail: "NDNCAIR@nitda.gov.ng", headshipType: "Substantive", headTitle: "NDNCAIR" }),
  Object.freeze({ key: "ONDI", title: "Office for Nigerian Digital Innovation", email: "ONDI@nitda.gov.ng", headEmail: "NCONDI@nitda.gov.ng", headshipType: "Substantive", headTitle: "NCONDI" }),
  Object.freeze({ key: "AGS", title: "Administration and General Services Department", email: "", headEmail: "AGS@nitda.gov.ng", headshipType: "Substantive", headTitle: "DAGSD" }),
  Object.freeze({ key: "EA", title: "Executive Assistant to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "EA TO DGCEO" }),
  Object.freeze({ key: "EAA", title: "Executive Assistant (Automation) to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "EAA To DGCEO" }),
  Object.freeze({ key: "PA", title: "Personal Assistant to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "PA To DGCEO" }),
  Object.freeze({ key: "SA-SP", title: "Special Assistant (Strategic Partnerships) to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "SA (SP) to the DGCEO" }),
  Object.freeze({ key: "SA-PF", title: "Special Assistant (Policy Formulation) to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "SA(PF) TO DGCEO" }),
  Object.freeze({ key: "PU", title: "Procurement", email: "PU@nitda.gov.ng", headEmail: "HPU@nitda.gov.ng", headshipType: "Substantive", headTitle: "HPU" }),
  Object.freeze({ key: "PM", title: "Project Management Department", email: "PM@nitda.gov.ng", headEmail: "", headshipType: "Acting", headTitle: "Ag. DPM" }),
  Object.freeze({ key: "RCSD", title: "Reforms Coordination and Service Delivery Unit", email: "RCSD@nitda.gov.ng", headEmail: "HRCSD@nitda.gov.ng", headshipType: "Substantive", headTitle: "HRCSD" }),
  Object.freeze({ key: "RC", title: "Regulations and Compliance Department", email: "RC@nitda.gov.ng", headEmail: "DRC@nitda.gov.ng", headshipType: "Acting", headTitle: "Ag. DRC" }),
  Object.freeze({ key: "RD", title: "Research and Development Department", email: "RD@nitda.gov.ng", headEmail: "DRD@nitda.gov.ng", headshipType: "Substantive", headTitle: "DRD" }),
  Object.freeze({ key: "SA-IP", title: "Special Assistant (Innovation and Research) to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "SA (IR) to the DGCEO" }),
  Object.freeze({ key: "SERVICOM", title: "SERVICOM", email: "SERVICOM@nitda.gov.ng", headEmail: "HSERVICOM@nitda.gov.ng", headshipType: "Substantive", headTitle: "HSERVICOM" }),
  Object.freeze({ key: "SMP", title: "Stakeholders Management and Partnerships Department", email: "SMP@nitda.gov.ng", headEmail: "DSMP@nitda.gov.ng", headshipType: "Substantive", headTitle: "DSMP" }),
  Object.freeze({ key: "ZOC", title: "Zonal Office Coordination Department", email: "ZOC@nitda.gov.ng", headEmail: "DZOC@nitda.gov.ng", headshipType: "Substantive", headTitle: "DZOC" }),
  Object.freeze({ key: "SA-Admin", title: "Special Assistant (Administration) to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "SA (Admin) to the DGCEO" }),
  Object.freeze({ key: "SA-SC", title: "Special Assistant (Strategic Communications) to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "SA (SC) to the DGCEO" }),
  Object.freeze({ key: "SA-DT", title: "Special Assistant (Digital Transformation) to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "SA (DT) to the DGCEO" }),
  Object.freeze({ key: "SA-CS", title: "Special Assistant (Cyber Security) to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "SA (CS) to the DGCEO" }),
  Object.freeze({ key: "ITPCU", title: "IT Projects Clearance Unit", email: "ITPCU@NITDA.GOV.NG", headEmail: "HITPCU@NITDA.GOV.NG", headshipType: "Substantive", headTitle: "HITPCU" }),
  Object.freeze({ key: "NCSC", title: "NATIONAL CYBERSECURITY CONFERENCE", email: "ncscsecretariat@nitda.gov.ng", headEmail: "ncscsecretariat@nitda.gov.ng", headshipType: "", headTitle: "NCSC Secreteriat" }),
  Object.freeze({ key: "PPPU", title: "Public Private Partnerships Unit", email: "pppu@nitda.gov.ng", headEmail: "hpppu@nitda.gov.ng", headshipType: "Substantive", headTitle: "HPPPU" }),
  Object.freeze({ key: "CP", title: "Chief Protocol to DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "CP to DGCEO" }),
  Object.freeze({ key: "SA-SE", title: "Special Assistant (Strategy Execution) to the DGCEO", email: "", headEmail: "", headshipType: "DGCEO_Assistant", headTitle: "SA(SE) to the DGCEO" }),
  Object.freeze({ key: "SWZO", title: "South West Zonal Office", email: "swzo@nitda.gov.ng", headEmail: "", headshipType: "Substantive", headTitle: "HSWZO" }),
  Object.freeze({ key: "NEZO", title: "North East Zonal Office", email: "nezo@nitda.gov.ng", headEmail: "hnezo@nitda.gov.ng", headshipType: "Substantive", headTitle: "HNEZO" }),
  Object.freeze({ key: "ICEGOV", title: "ICEGOV", email: "icegov@nitda.gov.ng", headEmail: "Icegov@nitda.gov.ng", headshipType: "", headTitle: "ICEGOV" }),
  Object.freeze({ key: "DNCE", title: "Digital Nigeria International Conference", email: "digitalnigeria@nitda.gov.ng", headEmail: "", headshipType: "Substantive", headTitle: "Digital Nigeria International Conference" }),
  Object.freeze({ key: "SDO", title: "Special Duties Office", email: "sdo@nitda.gov.ng", headEmail: "Dsdo@nitda.gov.ng", headshipType: "Substantive", headTitle: "DSDO" }),
]);

/** key → unit, for the resolvers that only hold a DSU key. */
export const UnitByKey = Object.freeze(Object.fromEntries(
  OrganizationalUnits.map(u => [u.key.toUpperCase(), u]),
));

/** The mailbox to address for a unit: its head's post, else the unit's own. '' when neither. */
export function mailboxFor(dsuKey) {
  const u = UnitByKey[String(dsuKey || '').trim().toUpperCase()];
  return u ? (u.headEmail || u.email || '') : '';
}
