#!/usr/bin/env node
/**
 * Describe the SHAPE of the URLs in a values file. Prints no URL, no host, no signature —
 * only the structure, so the output is safe to paste anywhere.
 *
 *   node scripts/describe-values.mjs ~/dgo-values.txt
 */
import { readFileSync, existsSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const arg = process.argv[2];
if (!arg) { console.error('usage: node scripts/describe-values.mjs <values file>'); process.exit(2); }
const file = path.resolve(String(arg).replace(/^~(?=$|[\\/])/, os.homedir()));
if (!existsSync(file)) { console.error(`not found: ${file}`); process.exit(1); }

const rows = [];
for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
  const t = line.trim();
  if (!t || t.startsWith('#')) continue;
  const m = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(t);
  if (!m) continue;
  const key = m[1].replace(/^(DGO|PF)_ENDPOINT_/, '');
  const val = m[2].trim().replace(/^(['"])(.*)\1$/, '$2');
  if (!val) { rows.push({ key, shape: '(empty)' }); continue; }
  let u;
  try { u = new URL(val); } catch { rows.push({ key, shape: `NOT A URL — starts "${val.slice(0, 12)}…", ${val.length} chars` }); continue; }
  const hostKind = /\.environment\.api\.powerplatform\.com$/i.test(u.hostname) ? 'powerplatform'
    : /\.logic\.azure\.com$/i.test(u.hostname) ? 'logic.azure.com'
    : /\.flow\.microsoft\.com$/i.test(u.hostname) ? 'flow.microsoft.com'
    : `OTHER (${u.hostname.split('.').slice(-3).join('.')})`;
  const pathShape = u.pathname
    .replace(/\/[0-9a-fA-F]{32}\//g, '/<32hex>/')
    .replace(/\/[0-9a-fA-F-]{36}\//g, '/<guid>/');
  const q = [...u.searchParams.keys()].sort();
  const sig = u.searchParams.get('sig');
  /* `sig` present as a parameter but empty is the template waiting to be filled in;
     `sig` absent altogether is a URL that lost its query. searchParams.get returns '' for the
     first and null for the second, which is exactly the distinction needed. */
  const awaiting = sig === '' && q.length > 1;
  rows.push({ key, shape: `${u.protocol}//<${hostKind}>${u.port ? ':' + u.port : ''}${pathShape}`,
              query: q.join(','), sigLen: sig ? sig.length : 0, awaiting,
              sigOk: sig ? /^[A-Za-z0-9_-]+$/.test(sig) : false });
}

const W = Math.max(...rows.map((r) => r.key.length), 8);
console.log(`\n${rows.length} entries in ${path.basename(file)} — shapes only, no URL printed\n`);
for (const r of rows) {
  if (!r.query) { console.log(`  ${r.key.padEnd(W)}  ${r.shape}`); continue; }
  console.log(`  ${r.key.padEnd(W)}  ${r.shape}`);
  console.log(`  ${' '.repeat(W)}  query=[${r.query}]  sig=${r.sigLen} chars${r.sigOk ? '' : ' NON-BASE64URL'}`);
}
const forms = [...new Set(rows.filter((r) => r.query).map((r) => r.shape))];
console.log(`\ndistinct URL forms: ${forms.length}`);
forms.forEach((f) => console.log(`  ${f}`));
const lens = [...new Set(rows.filter((r) => r.sigLen).map((r) => r.sigLen))].sort((a, b) => a - b);
console.log(`signature lengths seen: ${lens.join(', ') || 'none'}`);

/* ------------------------------------------------------------------ *
 * A verdict, so this can be used before `npm run setup` rather than only after
 * something has gone wrong.
 *
 * Describing a values file and JUDGING one are different jobs, and this script only did
 * the first. That is the wrong half to have when the reader is a person who has just
 * pasted two 300-character URLs off a phone screen: the failure that actually happens is
 * a URL truncated at the `&`, which is still a valid-looking https URL on the right host
 * with the right path — it simply has no `sig`. Printed among four other lines of shape,
 * `sig=0 chars` is easy to read past. Named as a problem, it is not.
 *
 * CANONICAL_SIGNATURE_LENGTH is 43 and there is no legitimate variation: the signature is
 * base64url of an HMAC-SHA256, which is 32 bytes, which is 43 characters unpadded. So a
 * short one is a truncation and a long one is prose glued onto the end — both are the same
 * finding, and both mean the value will 401 rather than work.
 *
 * Exit 1 only with --strict, so the plain descriptive use this script already had is
 * unchanged for anyone who was running it.
 * ------------------------------------------------------------------ */

const SIGNATURE_LENGTH = 43;
const problems = [];
for (const r of rows) {
  if (r.shape === '(empty)') { problems.push(`${r.key} — no value`); continue; }
  if (!r.query) { problems.push(`${r.key} — ${r.shape}`); continue; }
  if (r.sigLen === 0) {
    /* Two very different situations produce a signature-less URL, and telling someone the wrong
       one sends them to re-copy a URL that was fine. A line generated by
       `npm run values:template` arrives complete but for the signature — every other parameter
       present, ending at `sig=` — and simply has not been filled in yet. A line someone pasted
       by hand and lost the query on has no `sig` parameter at all. The first is an unfinished
       step; the second is a bad copy. `awaiting` distinguishes them. */
    problems.push(r.awaiting
      ? `${r.key} — the URL is complete but its signature is blank. Open ${r.flow || 'the flow'},`
        + ` copy the part of its trigger URL after "sig=", and paste it at the end of this line.`
      : `${r.key} — no sig= parameter. The URL was almost certainly cut short at the `
        + `first "&" on copy; everything after "?" has to come with it.`);
  } else if (!r.sigOk) {
    problems.push(`${r.key} — sig contains characters a signature cannot contain`);
  } else if (r.sigLen !== SIGNATURE_LENGTH) {
    problems.push(`${r.key} — sig is ${r.sigLen} characters, not ${SIGNATURE_LENGTH}. `
      + `${r.sigLen < SIGNATURE_LENGTH ? 'Truncated on copy.' : 'Something was pasted onto the end of it.'}`);
  }
}

const STRICT = process.argv.includes('--strict');
if (problems.length) {
  console.log(`\n${problems.length} problem(s) — these values will not work:\n`);
  for (const p of problems) console.log(`  ✖  ${p}`);
  console.log('\nFix them in the values file and run this again. Nothing above is a credential.');
  if (STRICT) process.exit(1);
} else if (rows.length) {
  console.log(`\n✅ ${rows.length} value(s), all with a complete ${SIGNATURE_LENGTH}-character signature.`);
} else {
  console.log('\nNo entries found. Check the file has KEY=value lines and no stray quotes.');
  if (STRICT) process.exit(1);
}
