/* GENERATED FILE — do not edit by hand.
 * Built from docs/reference/http-flow-registry-spec.json by
 * scripts/build-flow-registry-provisioner.mjs. Edit the specification and re-run.
 */
/*
 * GOVERNANCE-TENANT-RUNBOOK.md Step 5 — provision the HTTP flow registry lists that the decision
 * authorised. Browser console; no PowerShell.
 *
 *   7 lists · 102 columns · 42 indexed · 7 unique
 *   on https://nitdanigeria.sharepoint.com/sites/DGO_ECM_GOVERNANCE
 *
 * NOTHING IS DEFERRED. Every list in the specification is either read or written by a
 *   corrected flow, or is the configuration list those flows read their parameters from.
 *   A provisioner that creates more than the flows need is how a deferral quietly becomes a
 *   deployment; one that creates fewer is how a runbook ends up telling an operator to exercise
 *   a flow against a list that does not exist. Either way, do not edit this file — the scope
 *   comes from scripts/lib/registry-provisioning-scope.mjs.
 *
 * WHY THIS ONE CREATES LISTS, AND WHY THAT IS THE RISKY PART
 *   Step 2's ten lists already existed, so that provisioner addresses every one by a GUID
 *   captured from the tenant. These three do not exist, and a list that does not exist has no
 *   GUID — so creation is unavoidably by title.
 *
 *   That is exactly the operation that produced GOV-02: a title-based create run twice leaves
 *   DGO_AuditLog and DGO_AuditLog_2, and a flow writing one while another reads the other both
 *   succeed while neither sees the other. So the title is used ONCE, to ask whether the list is
 *   already there:
 *
 *     1. GET the list by title. If it exists, take its GUID and create nothing.
 *     2. Only on 404, POST to create it — then read back the GUID SharePoint assigned.
 *     3. Every column and every index after that addresses the GUID.
 *
 *   Run it twice and the second run creates nothing. That is the property GOV-02 was missing.
 *
 * WHAT TO DO WITH THE OUTPUT
 *   It prints the GUID of each list. Those GUIDs must be recorded in
 *   docs/reference/governance-list-registry.json, or the repository goes on describing these
 *   lists as unprovisioned while the tenant has them.
 *
 * HOW TO RUN
 *   1. Sign in and open any page on
 *      https://nitdanigeria.sharepoint.com/sites/DGO_ECM_GOVERNANCE
 *   2. F12 → Console.
 *   3. Paste. It reports what it WOULD do and changes nothing.
 *   4. Read the table. Then set DRY_RUN to false and paste again.
 *
 * PERMISSION REQUIRED
 *   Manage Lists on DGO_ECM_GOVERNANCE. Site Owner is enough.
 */

const DRY_RUN = true;

const SITE = "https://nitdanigeria.sharepoint.com/sites/DGO_ECM_GOVERNANCE";
const SPEC = {
  "totals": {
    "lists": 7,
    "fields": 102,
    "indexed": 42,
    "unique": 7
  },
  "lists": [
    {
      "listTitle": "DGO_HTTPFlowRegistry",
      "description": "Current authoritative HTTP flow truth",
      "baseTemplate": 100,
      "uniqueKey": "RegistryKey",
      "versioning": true,
      "fields": [
        {
          "internalName": "RegistryKey",
          "displayName": "RegistryKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": true,
          "schemaXml": "<Field Type='Text' DisplayName='RegistryKey' Name='RegistryKey' StaticName='RegistryKey' Required='TRUE' MaxLength='255' Indexed='TRUE' EnforceUniqueValues='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "FlowId",
          "displayName": "FlowId",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='FlowId' Name='FlowId' StaticName='FlowId' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "EnvironmentId",
          "displayName": "EnvironmentId",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='EnvironmentId' Name='EnvironmentId' StaticName='EnvironmentId' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "EnvironmentName",
          "displayName": "EnvironmentName",
          "fieldType": "Text",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='EnvironmentName' Name='EnvironmentName' StaticName='EnvironmentName' Required='FALSE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "FlowName",
          "displayName": "FlowName",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='FlowName' Name='FlowName' StaticName='FlowName' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "SystemName",
          "displayName": "SystemName",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='SystemName' Name='SystemName' StaticName='SystemName' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "BusinessProcess",
          "displayName": "BusinessProcess",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='BusinessProcess' Name='BusinessProcess' StaticName='BusinessProcess' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "FlowDescription",
          "displayName": "FlowDescription",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='FlowDescription' Name='FlowDescription' StaticName='FlowDescription' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "TechnicalOwnerEmail",
          "displayName": "TechnicalOwnerEmail",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='TechnicalOwnerEmail' Name='TechnicalOwnerEmail' StaticName='TechnicalOwnerEmail' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "BusinessOwnerEmail",
          "displayName": "BusinessOwnerEmail",
          "fieldType": "Text",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='BusinessOwnerEmail' Name='BusinessOwnerEmail' StaticName='BusinessOwnerEmail' Required='FALSE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "SupportEmail",
          "displayName": "SupportEmail",
          "fieldType": "Text",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='SupportEmail' Name='SupportEmail' StaticName='SupportEmail' Required='FALSE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "HttpMethod",
          "displayName": "HttpMethod",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='HttpMethod' Name='HttpMethod' StaticName='HttpMethod' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "EndpointRedacted",
          "displayName": "EndpointRedacted",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='EndpointRedacted' Name='EndpointRedacted' StaticName='EndpointRedacted' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "EndpointFingerprint",
          "displayName": "EndpointFingerprint",
          "fieldType": "Text",
          "required": false,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='EndpointFingerprint' Name='EndpointFingerprint' StaticName='EndpointFingerprint' Required='FALSE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "AuthenticationMode",
          "displayName": "AuthenticationMode",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='AuthenticationMode' Name='AuthenticationMode' StaticName='AuthenticationMode' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DataClassification",
          "displayName": "DataClassification",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='DataClassification' Name='DataClassification' StaticName='DataClassification' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "Criticality",
          "displayName": "Criticality",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='Criticality' Name='Criticality' StaticName='Criticality' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LifecycleStatus",
          "displayName": "LifecycleStatus",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='LifecycleStatus' Name='LifecycleStatus' StaticName='LifecycleStatus' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DefinitionVersion",
          "displayName": "DefinitionVersion",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='DefinitionVersion' Name='DefinitionVersion' StaticName='DefinitionVersion' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DefinitionFingerprint",
          "displayName": "DefinitionFingerprint",
          "fieldType": "Text",
          "required": false,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='DefinitionFingerprint' Name='DefinitionFingerprint' StaticName='DefinitionFingerprint' Required='FALSE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RequestSchemaJson",
          "displayName": "RequestSchemaJson",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='RequestSchemaJson' Name='RequestSchemaJson' StaticName='RequestSchemaJson' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ResponseContractJson",
          "displayName": "ResponseContractJson",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='ResponseContractJson' Name='ResponseContractJson' StaticName='ResponseContractJson' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LastRegisteredUtc",
          "displayName": "LastRegisteredUtc",
          "fieldType": "DateTime",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='LastRegisteredUtc' Name='LastRegisteredUtc' StaticName='LastRegisteredUtc' Required='TRUE' Format='DateTime' FriendlyDisplayFormat='Disabled' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LastSeenUtc",
          "displayName": "LastSeenUtc",
          "fieldType": "DateTime",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='LastSeenUtc' Name='LastSeenUtc' StaticName='LastSeenUtc' Required='TRUE' Format='DateTime' FriendlyDisplayFormat='Disabled' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LastSuccessfulCallUtc",
          "displayName": "LastSuccessfulCallUtc",
          "fieldType": "DateTime",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='LastSuccessfulCallUtc' Name='LastSuccessfulCallUtc' StaticName='LastSuccessfulCallUtc' Required='FALSE' Format='DateTime' FriendlyDisplayFormat='Disabled' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LastFailureUtc",
          "displayName": "LastFailureUtc",
          "fieldType": "DateTime",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='LastFailureUtc' Name='LastFailureUtc' StaticName='LastFailureUtc' Required='FALSE' Format='DateTime' FriendlyDisplayFormat='Disabled' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LastAuditUtc",
          "displayName": "LastAuditUtc",
          "fieldType": "DateTime",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='LastAuditUtc' Name='LastAuditUtc' StaticName='LastAuditUtc' Required='FALSE' Format='DateTime' FriendlyDisplayFormat='Disabled' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "TotalExecutions",
          "displayName": "TotalExecutions",
          "fieldType": "Number",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Number' DisplayName='TotalExecutions' Name='TotalExecutions' StaticName='TotalExecutions' Required='TRUE' Decimals='0' Min='0' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "SuccessfulExecutions",
          "displayName": "SuccessfulExecutions",
          "fieldType": "Number",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Number' DisplayName='SuccessfulExecutions' Name='SuccessfulExecutions' StaticName='SuccessfulExecutions' Required='TRUE' Decimals='0' Min='0' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "FailedExecutions",
          "displayName": "FailedExecutions",
          "fieldType": "Number",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Number' DisplayName='FailedExecutions' Name='FailedExecutions' StaticName='FailedExecutions' Required='TRUE' Decimals='0' Min='0' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ConsecutiveFailures",
          "displayName": "ConsecutiveFailures",
          "fieldType": "Number",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Number' DisplayName='ConsecutiveFailures' Name='ConsecutiveFailures' StaticName='ConsecutiveFailures' Required='TRUE' Decimals='0' Min='0' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "AverageDurationMs",
          "displayName": "AverageDurationMs",
          "fieldType": "Number",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Number' DisplayName='AverageDurationMs' Name='AverageDurationMs' StaticName='AverageDurationMs' Required='TRUE' Decimals='0' Min='0' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "IsCompliant",
          "displayName": "IsCompliant",
          "fieldType": "Boolean",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Boolean' DisplayName='IsCompliant' Name='IsCompliant' StaticName='IsCompliant' Required='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ComplianceIssues",
          "displayName": "ComplianceIssues",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='ComplianceIssues' Name='ComplianceIssues' StaticName='ComplianceIssues' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RecordVersion",
          "displayName": "RecordVersion",
          "fieldType": "Number",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Number' DisplayName='RecordVersion' Name='RecordVersion' StaticName='RecordVersion' Required='TRUE' Decimals='0' Min='0' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "WorkflowId",
          "displayName": "WorkflowId",
          "fieldType": "Text",
          "required": false,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='WorkflowId' Name='WorkflowId' StaticName='WorkflowId' Required='FALSE' MaxLength='32' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        }
      ]
    },
    {
      "listTitle": "DGO_HTTPFlowContractVersions",
      "description": "Immutable contracts",
      "baseTemplate": 100,
      "uniqueKey": "ContractKey",
      "versioning": true,
      "fields": [
        {
          "internalName": "ContractKey",
          "displayName": "ContractKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": true,
          "schemaXml": "<Field Type='Text' DisplayName='ContractKey' Name='ContractKey' StaticName='ContractKey' Required='TRUE' MaxLength='255' Indexed='TRUE' EnforceUniqueValues='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RegistryKey",
          "displayName": "RegistryKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='RegistryKey' Name='RegistryKey' StaticName='RegistryKey' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "FlowId",
          "displayName": "FlowId",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='FlowId' Name='FlowId' StaticName='FlowId' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "EnvironmentId",
          "displayName": "EnvironmentId",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='EnvironmentId' Name='EnvironmentId' StaticName='EnvironmentId' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DefinitionVersion",
          "displayName": "DefinitionVersion",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='DefinitionVersion' Name='DefinitionVersion' StaticName='DefinitionVersion' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DefinitionFingerprint",
          "displayName": "DefinitionFingerprint",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='DefinitionFingerprint' Name='DefinitionFingerprint' StaticName='DefinitionFingerprint' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RequestSchemaJson",
          "displayName": "RequestSchemaJson",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='RequestSchemaJson' Name='RequestSchemaJson' StaticName='RequestSchemaJson' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ResponseContractJson",
          "displayName": "ResponseContractJson",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='ResponseContractJson' Name='ResponseContractJson' StaticName='ResponseContractJson' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DependenciesJson",
          "displayName": "DependenciesJson",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='DependenciesJson' Name='DependenciesJson' StaticName='DependenciesJson' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "SnapshotJson",
          "displayName": "SnapshotJson",
          "fieldType": "Note",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='SnapshotJson' Name='SnapshotJson' StaticName='SnapshotJson' Required='TRUE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "EffectiveFromUtc",
          "displayName": "EffectiveFromUtc",
          "fieldType": "DateTime",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='EffectiveFromUtc' Name='EffectiveFromUtc' StaticName='EffectiveFromUtc' Required='TRUE' Format='DateTime' FriendlyDisplayFormat='Disabled' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "EffectiveToUtc",
          "displayName": "EffectiveToUtc",
          "fieldType": "DateTime",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='EffectiveToUtc' Name='EffectiveToUtc' StaticName='EffectiveToUtc' Required='FALSE' Format='DateTime' FriendlyDisplayFormat='Disabled' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "IsCurrent",
          "displayName": "IsCurrent",
          "fieldType": "Boolean",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Boolean' DisplayName='IsCurrent' Name='IsCurrent' StaticName='IsCurrent' Required='TRUE' Group='DGO HTTP Flow Governance' />"
        }
      ]
    },
    {
      "listTitle": "DGO_HTTPFlowExecutionLedger",
      "description": "Execution ledger",
      "baseTemplate": 100,
      "uniqueKey": "ExecutionKey",
      "versioning": true,
      "fields": [
        {
          "internalName": "ExecutionKey",
          "displayName": "ExecutionKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": true,
          "schemaXml": "<Field Type='Text' DisplayName='ExecutionKey' Name='ExecutionKey' StaticName='ExecutionKey' Required='TRUE' MaxLength='255' Indexed='TRUE' EnforceUniqueValues='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RegistryKey",
          "displayName": "RegistryKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='RegistryKey' Name='RegistryKey' StaticName='RegistryKey' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "FlowId",
          "displayName": "FlowId",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='FlowId' Name='FlowId' StaticName='FlowId' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "EnvironmentId",
          "displayName": "EnvironmentId",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='EnvironmentId' Name='EnvironmentId' StaticName='EnvironmentId' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RunId",
          "displayName": "RunId",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='RunId' Name='RunId' StaticName='RunId' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "CorrelationId",
          "displayName": "CorrelationId",
          "fieldType": "Text",
          "required": false,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='CorrelationId' Name='CorrelationId' StaticName='CorrelationId' Required='FALSE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "StartedUtc",
          "displayName": "StartedUtc",
          "fieldType": "DateTime",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='StartedUtc' Name='StartedUtc' StaticName='StartedUtc' Required='TRUE' Format='DateTime' FriendlyDisplayFormat='Disabled' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "CompletedUtc",
          "displayName": "CompletedUtc",
          "fieldType": "DateTime",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='CompletedUtc' Name='CompletedUtc' StaticName='CompletedUtc' Required='TRUE' Format='DateTime' FriendlyDisplayFormat='Disabled' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DurationMs",
          "displayName": "DurationMs",
          "fieldType": "Number",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Number' DisplayName='DurationMs' Name='DurationMs' StaticName='DurationMs' Required='TRUE' Decimals='0' Min='0' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "Outcome",
          "displayName": "Outcome",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='Outcome' Name='Outcome' StaticName='Outcome' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "HttpStatusCode",
          "displayName": "HttpStatusCode",
          "fieldType": "Number",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Number' DisplayName='HttpStatusCode' Name='HttpStatusCode' StaticName='HttpStatusCode' Required='FALSE' Decimals='0' Min='0' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "CallerSystem",
          "displayName": "CallerSystem",
          "fieldType": "Text",
          "required": false,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='CallerSystem' Name='CallerSystem' StaticName='CallerSystem' Required='FALSE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ErrorCode",
          "displayName": "ErrorCode",
          "fieldType": "Text",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='ErrorCode' Name='ErrorCode' StaticName='ErrorCode' Required='FALSE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ErrorMessage",
          "displayName": "ErrorMessage",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='ErrorMessage' Name='ErrorMessage' StaticName='ErrorMessage' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ExecutionMetadataJson",
          "displayName": "ExecutionMetadataJson",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='ExecutionMetadataJson' Name='ExecutionMetadataJson' StaticName='ExecutionMetadataJson' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        }
      ]
    },
    {
      "listTitle": "DGO_HTTPFlowDependencies",
      "description": "Flow dependencies",
      "baseTemplate": 100,
      "uniqueKey": "DependencyKey",
      "versioning": true,
      "fields": [
        {
          "internalName": "DependencyKey",
          "displayName": "DependencyKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": true,
          "schemaXml": "<Field Type='Text' DisplayName='DependencyKey' Name='DependencyKey' StaticName='DependencyKey' Required='TRUE' MaxLength='255' Indexed='TRUE' EnforceUniqueValues='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RegistryKey",
          "displayName": "RegistryKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='RegistryKey' Name='RegistryKey' StaticName='RegistryKey' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "Direction",
          "displayName": "Direction",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='Direction' Name='Direction' StaticName='Direction' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DependencyType",
          "displayName": "DependencyType",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='DependencyType' Name='DependencyType' StaticName='DependencyType' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DependencyIdentifier",
          "displayName": "DependencyIdentifier",
          "fieldType": "Text",
          "required": false,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='DependencyIdentifier' Name='DependencyIdentifier' StaticName='DependencyIdentifier' Required='FALSE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DependencyEndpointRedacted",
          "displayName": "DependencyEndpointRedacted",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='DependencyEndpointRedacted' Name='DependencyEndpointRedacted' StaticName='DependencyEndpointRedacted' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "IsCritical",
          "displayName": "IsCritical",
          "fieldType": "Boolean",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Boolean' DisplayName='IsCritical' Name='IsCritical' StaticName='IsCritical' Required='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LifecycleStatus",
          "displayName": "LifecycleStatus",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='LifecycleStatus' Name='LifecycleStatus' StaticName='LifecycleStatus' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LastConfirmedUtc",
          "displayName": "LastConfirmedUtc",
          "fieldType": "DateTime",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='LastConfirmedUtc' Name='LastConfirmedUtc' StaticName='LastConfirmedUtc' Required='TRUE' Format='DateTime' FriendlyDisplayFormat='Disabled' Group='DGO HTTP Flow Governance' />"
        }
      ]
    },
    {
      "listTitle": "DGO_HTTPFlowRegistryExceptions",
      "description": "Governance exceptions",
      "baseTemplate": 100,
      "uniqueKey": "ExceptionKey",
      "versioning": true,
      "fields": [
        {
          "internalName": "ExceptionKey",
          "displayName": "ExceptionKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": true,
          "schemaXml": "<Field Type='Text' DisplayName='ExceptionKey' Name='ExceptionKey' StaticName='ExceptionKey' Required='TRUE' MaxLength='255' Indexed='TRUE' EnforceUniqueValues='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RegistryKey",
          "displayName": "RegistryKey",
          "fieldType": "Text",
          "required": false,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='RegistryKey' Name='RegistryKey' StaticName='RegistryKey' Required='FALSE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "FlowId",
          "displayName": "FlowId",
          "fieldType": "Text",
          "required": false,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='FlowId' Name='FlowId' StaticName='FlowId' Required='FALSE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RunId",
          "displayName": "RunId",
          "fieldType": "Text",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='RunId' Name='RunId' StaticName='RunId' Required='FALSE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ExceptionType",
          "displayName": "ExceptionType",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='ExceptionType' Name='ExceptionType' StaticName='ExceptionType' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "Severity",
          "displayName": "Severity",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='Severity' Name='Severity' StaticName='Severity' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "Status",
          "displayName": "Status",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='Status' Name='Status' StaticName='Status' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "Details",
          "displayName": "Details",
          "fieldType": "Note",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='Details' Name='Details' StaticName='Details' Required='TRUE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DetectedUtc",
          "displayName": "DetectedUtc",
          "fieldType": "DateTime",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='DetectedUtc' Name='DetectedUtc' StaticName='DetectedUtc' Required='TRUE' Format='DateTime' FriendlyDisplayFormat='Disabled' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ResolvedUtc",
          "displayName": "ResolvedUtc",
          "fieldType": "DateTime",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='ResolvedUtc' Name='ResolvedUtc' StaticName='ResolvedUtc' Required='FALSE' Format='DateTime' FriendlyDisplayFormat='Disabled' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "AssignedToEmail",
          "displayName": "AssignedToEmail",
          "fieldType": "Text",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='AssignedToEmail' Name='AssignedToEmail' StaticName='AssignedToEmail' Required='FALSE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "DiagnosticJson",
          "displayName": "DiagnosticJson",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='DiagnosticJson' Name='DiagnosticJson' StaticName='DiagnosticJson' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        }
      ]
    },
    {
      "listTitle": "DGO_HTTPFlowRegistryConfiguration",
      "description": "Registry configuration",
      "baseTemplate": 100,
      "uniqueKey": "ConfigKey",
      "versioning": true,
      "fields": [
        {
          "internalName": "ConfigKey",
          "displayName": "ConfigKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": true,
          "schemaXml": "<Field Type='Text' DisplayName='ConfigKey' Name='ConfigKey' StaticName='ConfigKey' Required='TRUE' MaxLength='255' Indexed='TRUE' EnforceUniqueValues='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ConfigValue",
          "displayName": "ConfigValue",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='ConfigValue' Name='ConfigValue' StaticName='ConfigValue' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ValueType",
          "displayName": "ValueType",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='ValueType' Name='ValueType' StaticName='ValueType' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "IsSecret",
          "displayName": "IsSecret",
          "fieldType": "Boolean",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Boolean' DisplayName='IsSecret' Name='IsSecret' StaticName='IsSecret' Required='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ConfigDescription",
          "displayName": "ConfigDescription",
          "fieldType": "Note",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Note' DisplayName='ConfigDescription' Name='ConfigDescription' StaticName='ConfigDescription' Required='FALSE' NumLines='10' RichText='FALSE' AppendOnly='FALSE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "IsEnabled",
          "displayName": "IsEnabled",
          "fieldType": "Boolean",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Boolean' DisplayName='IsEnabled' Name='IsEnabled' StaticName='IsEnabled' Required='TRUE' Group='DGO HTTP Flow Governance' />"
        }
      ]
    },
    {
      "listTitle": "DGO_HTTPFlowConsumerRegistry",
      "description": "Consumer registry",
      "baseTemplate": 100,
      "uniqueKey": "ConsumerKey",
      "versioning": true,
      "fields": [
        {
          "internalName": "ConsumerKey",
          "displayName": "ConsumerKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": true,
          "schemaXml": "<Field Type='Text' DisplayName='ConsumerKey' Name='ConsumerKey' StaticName='ConsumerKey' Required='TRUE' MaxLength='255' Indexed='TRUE' EnforceUniqueValues='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "RegistryKey",
          "displayName": "RegistryKey",
          "fieldType": "Text",
          "required": true,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='RegistryKey' Name='RegistryKey' StaticName='RegistryKey' Required='TRUE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ConsumerName",
          "displayName": "ConsumerName",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='ConsumerName' Name='ConsumerName' StaticName='ConsumerName' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ConsumerType",
          "displayName": "ConsumerType",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='ConsumerType' Name='ConsumerType' StaticName='ConsumerType' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ConsumerIdentifier",
          "displayName": "ConsumerIdentifier",
          "fieldType": "Text",
          "required": false,
          "indexed": true,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='ConsumerIdentifier' Name='ConsumerIdentifier' StaticName='ConsumerIdentifier' Required='FALSE' MaxLength='255' Indexed='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "OwnerEmail",
          "displayName": "OwnerEmail",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='OwnerEmail' Name='OwnerEmail' StaticName='OwnerEmail' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ExpectedAuthentication",
          "displayName": "ExpectedAuthentication",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='ExpectedAuthentication' Name='ExpectedAuthentication' StaticName='ExpectedAuthentication' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "IsApproved",
          "displayName": "IsApproved",
          "fieldType": "Boolean",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Boolean' DisplayName='IsApproved' Name='IsApproved' StaticName='IsApproved' Required='TRUE' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "ApprovedUtc",
          "displayName": "ApprovedUtc",
          "fieldType": "DateTime",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='ApprovedUtc' Name='ApprovedUtc' StaticName='ApprovedUtc' Required='FALSE' Format='DateTime' FriendlyDisplayFormat='Disabled' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LastObservedUtc",
          "displayName": "LastObservedUtc",
          "fieldType": "DateTime",
          "required": false,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='DateTime' DisplayName='LastObservedUtc' Name='LastObservedUtc' StaticName='LastObservedUtc' Required='FALSE' Format='DateTime' FriendlyDisplayFormat='Disabled' Group='DGO HTTP Flow Governance' />"
        },
        {
          "internalName": "LifecycleStatus",
          "displayName": "LifecycleStatus",
          "fieldType": "Text",
          "required": true,
          "indexed": false,
          "unique": false,
          "schemaXml": "<Field Type='Text' DisplayName='LifecycleStatus' Name='LifecycleStatus' StaticName='LifecycleStatus' Required='TRUE' MaxLength='255' Group='DGO HTTP Flow Governance' />"
        }
      ]
    }
  ]
};

(async () => {
  const VERBOSE = 'application/json;odata=verbose';
  const NOMETA = 'application/json;odata=nometadata';

  const send = async (url, init, attempt = 0) => {
    const res = await fetch(url, { credentials: 'include', ...init });
    if ((res.status === 429 || res.status === 503) && attempt < 4) {
      const wait = (Number(res.headers.get('Retry-After')) || 2 ** attempt) * 1000;
      console.warn(`  throttled, waiting ${wait / 1000}s`);
      await new Promise((r) => setTimeout(r, wait));
      return send(url, init, attempt + 1);
    }
    return res;
  };

  const detail = async (res) => {
    const text = await res.text();
    let msg = text;
    try {
      const body = JSON.parse(text);
      const err = body['odata.error'] || body.error || body;
      msg = err?.message?.value ?? err?.message ?? err?.Message ?? text;
      if (err?.code) msg = `${msg} [${err.code}]`;
    } catch { /* keep the raw body */ }
    return `${res.status} ${String(msg).trim()}`;
  };

  const digestFor = async () => {
    const res = await send(`${SITE}/_api/contextinfo`, { method: 'POST', headers: { Accept: VERBOSE } });
    if (!res.ok) throw new Error(`contextinfo ${res.status} — are you signed in, and a member of this site?`);
    return (await res.json()).d.GetContextWebInformation.FormDigestValue;
  };

  /** The one title lookup. Returns the GUID, or null when the list is genuinely absent. */
  const findByTitle = async (title) => {
    const res = await send(
      `${SITE}/_api/web/lists/getbytitle('${encodeURIComponent(title)}')?$select=Id,Title,ItemCount`,
      { headers: { Accept: NOMETA } });
    if (res.status === 404) return null;
    if (!res.ok) throw new Error(await detail(res));
    const body = await res.json();
    return { guid: body.Id, itemCount: body.ItemCount };
  };

  const createList = async (digest, l) => {
    const res = await send(`${SITE}/_api/web/lists`, {
      method: 'POST',
      headers: { Accept: NOMETA, 'Content-Type': NOMETA, 'X-RequestDigest': digest },
      body: JSON.stringify({
        BaseTemplate: l.baseTemplate,
        Title: l.listTitle,
        Description: l.description || '',
        AllowContentTypes: true,
        ContentTypesEnabled: false,
        EnableVersioning: l.versioning === true,
      }),
    });
    if (!res.ok) throw new Error(await detail(res));
    return (await res.json()).Id;
  };

  const liveFields = async (guid) => {
    const res = await send(
      `${SITE}/_api/web/lists(guid'${guid}')/fields?$select=InternalName,Title,Indexed,FromBaseType,CanBeDeleted&$top=500`,
      { headers: { Accept: NOMETA } });
    if (!res.ok) throw new Error(`reading fields: ${await detail(res)}`);
    return new Map(((await res.json()).value || []).map((f) => [f.InternalName, f]));
  };

  /* A field inherited from the base type is SharePoint's, not the specification's. Counting one
     as present is the false positive that cost the 2026-09-09 run — see GOV-08. */
  const isCustom = (f) => f && f.FromBaseType !== true && f.CanBeDeleted !== false;

  const createField = async (guid, digest, xml) => {
    const res = await send(`${SITE}/_api/web/lists(guid'${guid}')/fields/createfieldasxml`, {
      method: 'POST',
      headers: { Accept: VERBOSE, 'Content-Type': VERBOSE, 'X-RequestDigest': digest },
      body: JSON.stringify({
        parameters: {
          __metadata: { type: 'SP.XmlSchemaFieldCreationInformation' },
          SchemaXml: xml,
          /* 8 = AddFieldInternalNameHint (take the internal name from the Name attribute),
             16 = AddFieldToDefaultView */
          Options: 24,
        },
      }),
    });
    if (!res.ok) throw new Error(await detail(res));
  };

  /* Indexed and unique are one MERGE, in that order within the same body: SharePoint refuses
     EnforceUniqueValues on a column that is not indexed. */
  const setIndexing = async (guid, digest, name, { indexed, unique }) => {
    const body = { __metadata: { type: 'SP.Field' } };
    if (indexed) body.Indexed = true;
    if (unique) body.EnforceUniqueValues = true;
    const res = await send(
      `${SITE}/_api/web/lists(guid'${guid}')/fields/getbyinternalnameortitle('${encodeURIComponent(name)}')`,
      {
        method: 'POST',
        headers: {
          Accept: VERBOSE, 'Content-Type': VERBOSE, 'X-RequestDigest': digest,
          'X-HTTP-Method': 'MERGE', 'IF-MATCH': '*',
        },
        body: JSON.stringify(body),
      },
    );
    if (!res.ok) throw new Error(await detail(res));
  };

  /* ── run ─────────────────────────────────────────────────────────────────────────────── */

  const ledger = [];
  const guids = [];
  let createdLists = 0, createdFields = 0, presentFields = 0, indexedNow = 0, failed = 0;

  console.log(
    `%c${DRY_RUN ? 'DRY RUN — ' : ''}${SPEC.totals.lists} list(s), ${SPEC.totals.fields} column(s), ${SPEC.totals.indexed} indexed, ${SPEC.totals.unique} unique`,
    'font-weight:bold;font-size:13px',
  );
  console.log(`%c${SITE}`, 'color:#888');

  let digest = null;
  try { digest = DRY_RUN ? 'dry-run' : await digestFor(); }
  catch (err) { console.error(err.message); return; }

  for (const l of SPEC.lists) {
    console.group(l.listTitle);
    let guid = null;

    try {
      const existing = await findByTitle(l.listTitle);
      if (existing) {
        guid = existing.guid;
        ledger.push({ list: l.listTitle, item: '(list)', action: 'present', detail: `${guid} · ${existing.itemCount} item(s)` });
      } else if (DRY_RUN) {
        ledger.push({ list: l.listTitle, item: '(list)', action: 'WOULD CREATE', detail: `BaseTemplate ${l.baseTemplate}` });
        for (const f of l.fields) {
          ledger.push({ list: l.listTitle, item: f.internalName, action: 'WOULD CREATE', detail: f.fieldType });
        }
        console.groupEnd();
        continue;
      } else {
        guid = await createList(digest, l);
        createdLists++;
        ledger.push({ list: l.listTitle, item: '(list)', action: 'CREATED', detail: guid });
      }
    } catch (err) {
      failed++;
      ledger.push({ list: l.listTitle, item: '(list)', action: 'FAILED', detail: err.message });
      console.groupEnd();
      continue;
    }

    guids.push({ listTitle: l.listTitle, listGuid: guid, uniqueKey: l.uniqueKey });

    let live;
    try { live = await liveFields(guid); }
    catch (err) {
      failed++;
      ledger.push({ list: l.listTitle, item: '(fields)', action: 'UNREADABLE', detail: err.message });
      console.groupEnd();
      continue;
    }

    for (const f of l.fields) {
      const existing = live.get(f.internalName);

      if (existing && !isCustom(existing)) {
        failed++;
        ledger.push({
          list: l.listTitle, item: f.internalName, action: 'RESERVED NAME',
          detail: `'${f.internalName}' is a SharePoint system field here (FromBaseType=${existing.FromBaseType}). `
            + 'The specification cannot own this name — rename it there.',
        });
        continue;
      }

      if (existing) {
        presentFields++;
        if ((f.indexed && existing.Indexed !== true) || f.unique) {
          if (DRY_RUN) {
            ledger.push({ list: l.listTitle, item: f.internalName, action: 'WOULD INDEX', detail: f.unique ? 'indexed + unique' : 'indexed' });
          } else {
            try { await setIndexing(guid, digest, f.internalName, f); indexedNow++; }
            catch (err) { failed++; ledger.push({ list: l.listTitle, item: f.internalName, action: 'INDEX FAILED', detail: err.message }); }
          }
        } else {
          ledger.push({ list: l.listTitle, item: f.internalName, action: 'present', detail: '' });
        }
        continue;
      }

      if (DRY_RUN) {
        ledger.push({ list: l.listTitle, item: f.internalName, action: 'WOULD CREATE', detail: f.fieldType });
        continue;
      }

      try {
        await createField(guid, digest, f.schemaXml);
        createdFields++;
        ledger.push({ list: l.listTitle, item: f.internalName, action: 'CREATED', detail: f.fieldType });
        if (f.indexed || f.unique) {
          try { await setIndexing(guid, digest, f.internalName, f); indexedNow++; }
          catch (err) { failed++; ledger.push({ list: l.listTitle, item: f.internalName, action: 'INDEX FAILED', detail: err.message }); }
        }
      } catch (err) {
        failed++;
        ledger.push({ list: l.listTitle, item: f.internalName, action: 'FAILED', detail: err.message });
      }
    }
    console.groupEnd();
  }

  console.table(ledger);
  console.log(
    `%c${DRY_RUN ? 'DRY RUN. Nothing was changed. ' : ''}`
    + `lists: ${createdLists} created · columns: ${createdFields} created, ${presentFields} present, ${indexedNow} indexed · ${failed} failed`,
    failed ? 'color:#b00;font-weight:bold' : 'font-weight:bold',
  );

  if (guids.length) {
    console.log('%cRECORD THESE GUIDs — the repository still calls these lists unprovisioned without them:', 'font-weight:bold');
    console.table(guids);
    console.log(JSON.stringify(guids, null, 2));
  }

  if (DRY_RUN) {
    console.log('%cSet DRY_RUN = false at the top of this file and paste again to apply.', 'font-weight:bold');
  } else if (!failed) {
    console.log('%cRe-run this file to verify: every row should read "present" and 0 created.', 'color:#080;font-weight:bold');
  }

  /* ── relay block ─────────────────────────────────────────────────────────────────────────
     One line of JSON, between two markers. Copy the line, not the table: a console.table copies
     as one unbroken string with its header repeated, and a whole-console paste also contains this
     script, whose source mentions every verdict the ledger can produce. */
  try {
    const _rows = (typeof ledger !== 'undefined' && Array.isArray(ledger)) ? ledger
      : (typeof summary !== 'undefined' && Array.isArray(summary)) ? summary : [];
    const _tally = {};
    for (const _r of _rows) {
      const _k = String(_r.action ?? _r.verdict ?? 'row');
      _tally[_k] = (_tally[_k] || 0) + 1;
    }
    const _payload = {
      script: "provision-flow-registry-lists.browser.js",
      mode: DRY_RUN ? 'dry-run' : 'apply',
      site: SITE,
      utc: new Date().toISOString(),
      rows: _rows.length,
      tally: _tally,
      ledger: _rows,
    };
    console.log('%c───────── RELAY: COPY THE SINGLE LINE BELOW ─────────', 'font-weight:bold');
    console.log(JSON.stringify(_payload));
    console.log('%c───────── END RELAY ─────────', 'font-weight:bold');
  } catch (_e) {
    /* Never let the relay turn a completed run into an apparent failure. */
    console.warn('relay block failed:', _e && _e.message);
  }

})();
